version: "3.5"

services:
  postgres:
    image: postgres:12.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=couscous
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
